import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { stripVTControlCharacters } from "node:util";
import { createJiti } from "jiti";
import { resolveHostPeerAliases } from "../src/runs/background/runner-aliases.ts";
import { createRun, saveRun, listRuns, storeRoot, writeJson } from "../src/store.ts";
import { createViewReader, emptyProgress } from "../src/progress.ts";

const host = process.env.PI_SUBAGENTS_PI_CODING_AGENT_PACKAGE_ROOT;
assert.ok(host);
const root = mkdtempSync(join(tmpdir(), "subagent-ui-"));
process.env.LOCALAPPDATA = root;
process.env.PI_CODING_AGENT_DIR = join(root, "agent");
mkdirSync(process.env.PI_CODING_AGENT_DIR, { recursive: true });
const { aliases, missing } = resolveHostPeerAliases(host);
assert.deepEqual(missing, []);
const jiti = createJiti(import.meta.url, { alias: aliases });
const sdk = await jiti.import<any>("@earendil-works/pi-coding-agent");
const tui = await jiti.import<any>("@earendil-works/pi-tui");
sdk.initTheme("dark");
const theme = sdk.getSelectListTheme ? (await jiti.import<any>(join(host, "dist/modes/interactive/theme/theme.js"))).getThemeByName("dark") : undefined;
const ui = await jiti.import<any>("../src/ui.ts");
const session = sdk.SessionManager.create(root, join(root, "sessions"));
session.appendMessage({ role: "assistant", content: [{ type: "text", text: "UI fixture session" }], api: "openai-completions", provider: "fixture", model: "parent", usage: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, totalTokens: 0, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 } }, stopReason: "stop", timestamp: Date.now() });
const runsRoot = storeRoot(session.getSessionId());
const contract = (task: string, depth = 1) => ({ version: 1 as const, task, cwd: root, model: { provider: "fixture", id: "parent", thinking: "off" as const }, context: "fresh" as const, depth: { depth, maxDepth: 2 }, timeoutMs: 60000 });
const done = createRun(runsRoot, contract("UI_COMPLETED_CASE"));
done.status = "completed"; saveRun(done); writeFileSync(done.outputPath, "# Completed\nUI_OUTPUT_OK", "utf8");
const failed = createRun(runsRoot, contract("UI_FAILED_CASE"));
failed.status = "failed"; failed.error = "UI_FAILURE_DETAIL"; saveRun(failed);
const active = createRun(runsRoot, contract("UI_ACTIVE_CASE"));
active.status = "running"; active.pid = process.pid; active.sessionFile = join(active.dir, "fixture-session.jsonl");
writeFileSync(active.sessionFile, [{ type: "message", message: { role: "user", content: "UI_TRANSCRIPT_USER" } }, { type: "message", message: { role: "toolResult", toolName: "bash", content: [{ type: "text", text: "UI_TRANSCRIPT_TOOL_RESULT" }] } }].map(e => JSON.stringify(e)).join("\n"), "utf8");
saveRun(active);
const child = createRun(join(active.dir, "children"), contract("UI_NESTED_CASE", 2));
child.status = "completed"; saveRun(child);
writeJson(join(active.dir, "progress.json"), { ...emptyProgress(), tools: 2, currentTool: "bash", activity: "执行 bash", text: "UI_STREAMING_TEXT", tokens: 42 });
const reader = createViewReader();
const commands = new Map<string, any>();
const handlers = new Map<string, any>();
const renderers = new Map<string, any>();
let widget: any;
let component: any;
let notices = 0;
let closeCustom: (() => void) | undefined;
const actions: any[] = [];
const controller = { root: runsRoot, list: () => listRuns(runsRoot), cancel: async (id: string, pause: boolean) => { actions.push([pause ? "pause" : "cancel", id]); }, resume: async (id: string) => { actions.push(["resume", id]); }, steer: (id: string, text: string) => { actions.push(["steer", id, text]); } };
const ctx = { hasUI: true, ui: { theme, setWidget: (_key: string, value: any) => { widget = value; }, notify() {}, confirm: async () => true, input: async () => "UI_STEER_MESSAGE", custom: (factory: any, options: any) => new Promise<void>(resolve => { assert.equal(options?.overlay, true, "Fullscreen viewport keys must be routed to the focused inspector overlay"); closeCustom = resolve; component = factory({ terminal: { rows: 40 }, requestRender() {} }, theme, {}, resolve); }) } };
const lifecycle = ui.registerRunUI({ registerCommand: (name: string, value: any) => commands.set(name, value), registerMessageRenderer: (name: string, value: any) => renderers.set(name, value), on: (name: string, cb: any) => handlers.set(name, cb), sendMessage: () => { notices++; } }, () => controller);
const frame = (name: string, c: any, width = 100) => {
  const lines = c.render(width);
  if (c === component) assert.ok(lines.length <= 35, "Inspector must leave room for Pi footer/editor framing");
  for (const line of lines) assert.ok(tui.visibleWidth(line) <= width, `${name}: line exceeds ${width} columns`);
  const text = lines.map(stripVTControlCharacters).join("\n");
  writeFileSync(join(root, `${name}.txt`), text, "utf8");
  return text;
};
try {
  assert.ok(commands.has("subagents-fleet") && commands.has("subagents"));
  handlers.get("session_start")({}, ctx);
  assert.equal(typeof widget, "function");
  assert.match(frame("roster", widget({}, theme)), /UI_ACTIVE_CASE/);
  const renderResult = ui.createRunResultRenderer();
  assert.match(frame("completed-card", renderResult({ details: { run: done, output: "# Completed\nUI_OUTPUT_OK" } }, { expanded: true }, theme)), /UI_OUTPUT_OK/);
  assert.match(frame("failed-card", renderResult({ details: { run: failed, output: "" } }, { expanded: false }, theme)), /UI_FAILURE_DETAIL/);
  const pending = commands.get("subagents-fleet").handler("", ctx);
  assert.ok(component);
  assert.match(frame("fleet", component), /fixture\/parent/);
  component.handleInput("\x1b[6~");
  assert.match(frame("fleet-output", component), /UI_STREAMING_TEXT/);
  component.handleInput("\r");
  component.handleInput("\x1b[6~");
  assert.match(frame("fleet-transcript", component), /UI_TRANSCRIPT_TOOL_RESULT/);
  component.handleInput("\x1b[B");
  assert.match(frame("nested", component), /深度 2\/2/);
  component.handleInput("\x1b[A");
  for (const key of ["p", "D", "c", "s"]) { component.handleInput(key); await new Promise(resolve => setImmediate(resolve)); }
  assert.deepEqual(actions.map(a => a[0]), ["pause", "cancel", "resume", "steer"]);
  assert.equal(actions[3][2], "UI_STEER_MESSAGE");
  ctx.ui.confirm = async () => false;
  component.handleInput("p");
  await new Promise(resolve => setImmediate(resolve));
  assert.equal(actions.length, 4, "Declined confirmation must not dispatch control");
  assert.match(frame("declined-control", component), /已取消操作/);
  frame("narrow", component, 24);
  for (const width of [36, 60, 80, 120]) frame(`width-${width}`, component, width);
  component.handleInput("\x1b");
  await pending;
  assert.equal(typeof widget, "function", "Closing inspector restores roster");
  assert.equal(notices, 0, "UI refreshes must never notify the model");
  assert.match(frame("notice", renderers.get("subagent-notice")({ details: { type: "complete", runId: done.id, status: "completed", outputPath: done.outputPath } }, { expanded: false }, theme)), /已完成/);
  assert.equal(reader(active).progress?.tools, 2);
  const longTask = "这是一次 UI 多行输出测试。" + "HIDDEN_LONG_INSTRUCTION ".repeat(80);
  const multiline = createRun(join(root, "render-only"), contract(longTask));
  multiline.status = "completed"; saveRun(multiline);
  const numbers = Array.from({ length: 101 }, (_, i) => String(i).padStart(3, "0"));
  writeFileSync(multiline.outputPath, numbers.join("\n"), "utf8");
  const callFrame = frame("multiline-call", ui.renderRunCall({ task: longTask, async: false }, theme));
  assert.equal(callFrame.split("\n").length, 1);
  assert.doesNotMatch(callFrame, /HIDDEN_LONG_INSTRUCTION/);
  const result = { details: { run: multiline, output: numbers.join("\n") } };
  const collapsed = frame("multiline-collapsed", renderResult(result, { expanded: false }, theme));
  assert.ok(collapsed.split("\n").length <= 7);
  assert.doesNotMatch(collapsed, /HIDDEN_LONG_INSTRUCTION|这是一次/);
  assert.match(collapsed, /另有 97 行/);
  const expanded = frame("multiline-expanded", renderResult(result, { expanded: true }, theme));
  assert.deepEqual(expanded.split("\n").map(line => line.trim()).filter(line => /^\d{3}$/.test(line)), numbers, "All 100 literal newlines must survive expansion");
  const multilineFleet = new ui.FleetComponent(() => [reader(multiline)], theme, () => {}, () => {}, () => 35, async () => {});
  const seen = new Set<string>();
  for (let page = 0; page < 8; page++) {
    for (const line of frame(`multiline-page-${page}`, multilineFleet).split("\n").map(line => line.trim())) if (/^\d{3}$/.test(line)) seen.add(line);
    multilineFleet.handleInput("\x1b[6~");
  }
  assert.deepEqual([...seen].sort(), numbers);
  multilineFleet.dispose();
  writeJson(join(multiline.dir, "progress.json"), { ...emptyProgress(), activity: "输出中", text: numbers.slice(0, 48).join("\n"), tokens: 0 });
  const staleFailed = { ...multiline, status: "failed", error: "fixture failure" };
  const failedPreview = frame("failed-partial", renderResult({ details: { run: staleFailed, output: "" } }, { expanded: false }, theme));
  assert.match(failedPreview, /未完成输出/);
  assert.doesNotMatch(failedPreview, /输出中|0 tokens/);
  assert.equal(ui.renderRoster([reader(staleFailed), reader(done)], theme, 100).length, 1, "Idle widget must not repeat finished tasks");
  const failedFleet = new ui.FleetComponent(() => [reader(staleFailed)], theme, () => {}, () => {}, () => 35, async () => {});
  const failedFrame = frame("failed-authoritative-state", failedFleet);
  assert.match(failedFrame, /当前：失败/);
  assert.doesNotMatch(failedFrame, /输出中/);
  failedFleet.dispose();
  console.log(`UI_COMPONENTS_PASS ${root}`);
} finally {
  component?.dispose(); closeCustom?.(); lifecycle.dispose();
  assert.equal(widget, undefined);
}
writeJson(join(process.env.PI_CODING_AGENT_DIR, "settings.json"), { quietStartup: true, defaultProvider: "fixture", defaultModel: "parent" });
writeJson(join(process.env.PI_CODING_AGENT_DIR, "models.json"), { providers: { fixture: { baseUrl: "http://127.0.0.1:1/v1", api: "openai-completions", apiKey: "fixture", models: [{ id: "parent", name: "UI Fixture", reasoning: false, input: ["text"], contextWindow: 128000, maxTokens: 2048, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 } }] } } });
writeJson(join(root, "fixture.json"), { root, agentDir: process.env.PI_CODING_AGENT_DIR, session: session.getSessionFile(), activeRun: join(active.dir, "status.json"), progress: join(active.dir, "progress.json"), extension: resolve("index.ts"), cli: join(host, "dist/cli.js") });
console.log(`PTY_FIXTURE ${join(root, "fixture.json")}`);
